In [1]:
import numpy as np
import pandas as pd

In [2]:
url= 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
names=["sepal-length",'sepal-width', 'petal-length', 'petal-width','class']
dataset=pd.read_csv(url,names=names)

In [3]:
dataset

sepal-length  sepal-width  petal-length  petal-width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
X=dataset.drop('class',1)
y=dataset["class"]

In [4]:
#
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test =train_test_split(X,y, test_size=0.2,random_state=123)

In [8]:
from sklearn.preprocessing import StandardScaler

In [10]:
sc=StandardScaler()

In [11]:
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [13]:
X_train.shape

(120, 4)

In [14]:
X_test.shape

(30, 4)

In [18]:
from sklearn.decomposition import PCA

In [19]:
pca=PCA()
X_train=pca.fit_transform(X_train)
X_test=pca.fit_transform(X_test)

In [21]:
explained_variance=pca.explained_variance_ratio_
explained_variance

array([0.74609362, 0.22378339, 0.02465195, 0.00547104])

In [22]:
pca=PCA(n_components=2)
X_train=pca.fit_transform(X_train)
X_test=pca.fit_transform(X_test)

In [26]:
explained_variance=pca.explained_variance_ratio_
explained_variance

array([0.74609362, 0.22378339])

In [5]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
clf = RandomForestClassifier(max_depth=2,random_state=123)

In [25]:
clf.fit(X_train,y_train)

RandomForestClassifier(max_depth=2, random_state=123)

In [30]:
# predicting test set to get result
y_pred=clf.predict(X_test)

In [34]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [35]:
cm=confusion_matrix(y_test,y_pred)

In [36]:
cm

array([[13,  0,  0],
       [ 0,  5,  1],
       [ 0,  0, 11]], dtype=int64)

In [37]:
print("Accuracy of the classifier is",accuracy_score(y_test,y_pred) )

Accuracy of the classifier is 0.9666666666666667
